### ISSUE TITLE
sqlite3.OperationalError: no such table: Frames

### ISSUE THREAD

**Issue by OrhunKok** [WEHI-Proteomics/tfde#2]
Hi I am having issues with running your pipeline, it seems that something goes wrong in the define-precursor-cuboids-pasef.py and it doesn't generate the required Frame table. 

Here is the last couple of lines of output where things seem to go wrong:

```
[('experiment_base_dir', '/home/kok.o'), ('experiment_name', 'JD1527'), ('run_name', 'JD1527_rep_1_GE5_1_1107'), ('mz_lower', 100), ('mz_upper', 1700), ('rt_lower', 0), ('rt_upper', 3000), ('ini_file', '/home/kok.o/tfde/pipeline/pasef-process-short-gradient.ini'), ('small_set_mode', False), ('ray_mode', 'cluster'), ('redis_address', None), ('proportion_of_cores_to_use', 0.9), ('denoised', False)]
loading the frames information
TaskFailed - taskid:define_precursor_cuboids
Command failed: 'python -u define-precursor-cuboids-pasef.py -eb /home/kok.o -en JD1527 -rn JD1527_rep_1_GE5_1_1107 -ini /home/kok.o/tfde/pipeline/pasef-process-short-gradient.ini -rl 0 -ru 3000 -rm cluster ' returned 1
```

Here is the error output:

```
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/pandas/io/sql.py", line 2056, in execute
    cur.execute(*args, **kwargs)
sqlite3.OperationalError: no such table: Frames

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "define-precursor-cuboids-pasef.py", line 194, in <module>
    frame_properties_df = load_frame_properties()
  File "define-precursor-cuboids-pasef.py", line 42, in load_frame_properties
    frames_properties_df = pd.read_sql_query("select * from Frames order by Id ASC;", db_conn)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/pandas/io/sql.py", line 436, in read_sql_query
    return pandas_sql.read_query(
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/pandas/io/sql.py", line 2116, in read_query
    cursor = self.execute(*args)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/pandas/io/sql.py", line 2068, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from Frames order by Id ASC;': no such table: Frames
```

I would appreciate if you could help me find what is occuring exactly and how I can fix it.

**Comment by OrhunKok** [comment]
Sorry this was a silly mistake on my part, I was not using targeted DDA data and so the program didn't know what to do.
