### ISSUE TITLE
sqlite3.OperationalError: no such table: GlobalMetaData

### ISSUE THREAD

**Issue by OrhunKok** [WEHI-Proteomics/tfde#3]
Hi I am trying to use 3DID but am running into an sql issue where it expects a metadata table.

Here is the full error:

```
TaskFailed
Command failed: 'rm /home/kok.o/JD1527/features-3did/exp-JD1527-run-JD1527_rep_1_GE5_1_1107-features-3did-dedup.feather' returned 1
TaskFailed
Command failed: 'rm /home/kok.o/JD1527/features-3did/exp-JD1527-run-JD1527_rep_1_GE5_1_1107-features-3did-ident.feather' returned 1
2022-12-10 13:43:29,758 INFO services.py:1245 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/pandas/io/sql.py", line 2056, in execute
    cur.execute(*args, **kwargs)
sqlite3.OperationalError: no such table: GlobalMetaData


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "detect-features-with-3did.py", line 759, in <module>
    data = alphatims.bruker.TimsTOF(RAW_DATABASE_NAME)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/alphatims/bruker.py", line 934, in __init__
    self._import_data_from_d_folder(
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/alphatims/bruker.py", line 981, in _import_data_from_d_folder
    ) = read_bruker_sql(bruker_d_folder_name, self._zeroth_frame)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/alphatims/bruker.py", line 182, in read_bruker_sql
    global_meta_data = pd.read_sql_query(
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/pandas/io/sql.py", line 436, in read_sql_query
    return pandas_sql.read_query(
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/pandas/io/sql.py", line 2116, in read_query
    cursor = self.execute(*args)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/pandas/io/sql.py", line 2068, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT * from GlobalMetaData': no such table: GlobalMetaData
2022-12-10 13:43:33,574 WARNING worker.py:1189 -- The agent on node d0132 failed with the following error:
Traceback (most recent call last):
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 354, in <module>
    loop.run_until_complete(agent.run())
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 144, in run
    modules = self._load_modules()
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 98, in _load_modules
    c = cls(self)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 148, in __init__
    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/ray/_private/metrics_agent.py", line 75, in __init__
    prometheus_exporter.new_stats_exporter(
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 333, in new_stats_exporter
    exporter = PrometheusStatsExporter(
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 266, in __init__
    self.serve_http()
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 320, in serve_http
    start_http_server(
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/prometheus_client/exposition.py", line 169, in start_wsgi_server
    TmpServer.address_family, addr = _get_best_family(addr, port)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/site-packages/prometheus_client/exposition.py", line 158, in _get_best_family
    infos = socket.getaddrinfo(address, port)
  File "/home/kok.o/miniconda/envs/TFDE/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

```

Here is my variable-minvi.sh:

```
#!/bin/bash

echo "JD1527, minvi 3000"
doit -f ./tfde/3did/execute.py clean en=JD1527 rn=JD1527_rep_1_GE5_1_1107 eb="/home/kok.o"
doit -f ./tfde/3did/execute.py pc=0.8 en=JD1527 rdn=JD1527_rep_1_GE5_1_1107.d rn=JD1527_rep_1_GE5_1_1107 minvi=3000 mw=10 eb="/home/kok.o"
echo
```
 
Do you know what could be causing this issue? I look forward to hearing your thoughts.

**Comment by DarylWM** [comment]
Hi Orhun. That error is raised by the AlphaTims library that 3DID is using to read the raw data. [This line](https://github.com/MannLabs/alphatims/blob/0f1275aaa779dc7c7e3dbf2707f14356b08c9e4b/alphatims/bruker.py#L189) is where it tries to read the run's metadata, but in your case that table is missing. Which version of the timsTOF otofControl software are you using?

**Comment by DarylWM** [comment]
Also sorry about the delay of my response. I didn't receive notification that issues had been raised, but hopefully I've changed the correct setting now.

**Comment by OrhunKok** [comment]
The version of the otofControl seems to be 6.2.

**Comment by DarylWM** [comment]
That's the same version I used. Use 'DB Browser for SQLite' (or a similar SQLite browser) to open the analysis.tdf file under the run's .d directory. You should have a schema like this.

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/1016303/208525378-3fc3b45f-81ee-46e6-961a-ed5ec02e98fc.png">

Let me know what you have.

**Comment by OrhunKok** [comment]
Here is what mine looks like:

![1](https://user-images.githubusercontent.com/59579802/208823032-29b4b28b-088a-4cfb-a326-e69d1fb85f0d.png)

**Comment by DarylWM** [comment]
And that schema is from the `analysis.tdf` database in `/home/kok.o/JD1527/raw-databases/JD1527_rep_1_GE5_1_1107.d` ?

Can you show me the stdout when you execute `variable-minvi.sh` ? We should see the statement from [this line](https://github.com/WEHI-Proteomics/tfde/blob/e83d3493a2b4258e8d3b0485cfcd20d190aa25f8/3did/detect-features-with-3did.py#L758).

**Comment by OrhunKok** [comment]
Yes that was the schema for /home/kok.o/JD1527/raw-databases/JD1527_rep_1_GE5_1_1107.d.

I believe my file transer might have not completed correctly before, so that is potentially why the script couldn't generate a metadata file. I tried running it again and I appear to have a different issue now.  I've attached both the stderr and stdout for the current issue I'm having. 

[minviOut.txt](https://github.com/WEHI-Proteomics/tfde/files/10279951/minviOut.txt)
[minviErr.txt](https://github.com/WEHI-Proteomics/tfde/files/10279952/minviErr.txt)

**Comment by DarylWM** [comment]
The table `GlobalMetaData` is created in the raw database by otofControl, not 3DID, so if it's missing, your run's file is incomplete.

As for the other issue, please post the output of the following command.

`python -u detect-features-with-3did.py -eb /scratch/kok.o -en JD1527 -rn JD1527_rep_1_GE5_1_1107 -mw 10 -pc 0.8 -ini /home/kok.o/tfde/3did/../pipeline/pasef-process-short-gradient.ini -rm cluster -minvi 600 -rl 10 -ru 3000 -mi 50 `

 If it's not related to the missing GlobalMetaData issue, can you please raise a new issue?
